name: "Zeytal Web App Feature Request"
description: Create a feature request for the web app
title: "[feat]: "
labels: ["feature request"]
body:
  - type: markdown
    attributes:
      value: |
        > Thanks for helping us improve zeytal. Before submitting, search for open/closed issues as the issue may have already been reported/addressed.

  - type: markdown
    attributes:
      value: |
        If you aren't sure this should be opened as an issue, [open a discussion instead](https://github.com/hyperstonk/zeytal-app/discussions).

  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: Tell us about your feature request
      placeholder: "I think this feature would be great because..."
      value: "Describe your feature request..."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the feature here.
      placeholder: ex. screenshots, Stack Overflow links, forum links, etc.
      value: "Additional details here..."
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Before submitting
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/hyperstonk/zeytal-app/blob/main/.github/CODE_OF_CONDUCT.md).
      options:
        - label: I've made research efforts and searched the documentation
          required: true
        - label: I've searched for existing issues and PRs
          required: true
